import { File } from './File';
import { Model } from './Model';

export interface Student extends Model {
	status: string;
	course: string;
	major: string;
	lrn: string;
	idNumber: string;
	lastName: string;
	firstName: string;
	middleName: string;
	number: string;
	email: string;
	facebook: string;
	address: string;
	sex: string;
	civilStatus: string;
	birthday: string;
	placeOfBirth: string;
	age: string;
	religion: string;
	height: string;
	weight: string;
	mothersName: string;
	mothersOccupation: string;
	fathersName: string;
	fathersOccupation: string;
	parentsAddress: string;
	parentsNumber: string;
	spouseName: string;
	spouseOccupation: string;
	spouseAddress: string;
	spouseNumber: string;
	elementarySchoolName: string;
	elementarySchoolAddress: string;
	elementarySchoolYearGraduated: string;
	elementarySchoolAwards: string;
	secondarySchoolName: string;
	secondarySchoolAddress: string;
	secondarySchoolYearGraduated: string;
	secondarySchoolAwards: string;
	collegeSchoolName: string;
	collegeSchoolAddress: string;
	collegeSchoolYearGraduated: string;
	collegeSchoolLastAttendance: string;
	talents: string;
	photo: File;
}
